export const LOAD_CUSTOMERS_DATA  = 'LOAD_CUSTOMERS_DATA '
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'

