export const LOAD_PURCHASES_DATA="LOAD_PURCHASES_DATA"
export const ADD_PURCHASE="ADD_PURCHASE" 
export const UPDATE_PURCHASE="UPDATE_PURCHASE"
export const DELETE_PRODUCT_PURCHASES="DELETE_PRODUCT_PURCHASES"
export const DELETE_CUSTOMER_PURCHASES="DELETE_CUSTOMER_PURCHASES"


